### ISSUE TITLE
Questions for 'data/category_emb' file

### ISSUE THREAD

**Issue by yjhong89** [WayneDW/sDeepFwFM#2]
Hi,

I am YJ Hong and thanks for your work.

While I am looking into this repository, it seems that there isn't any related code for generating 'data/category_emb' file,
which is used in data_preprocessing.

Can you let me know what it is and how generate this file please?

Thank you.

YJHong.

**Comment by WayneDW** [comment]
Hi, YJHong,

As you see from the main file: emb for tiny data corresponds to *map for large data.
result_dict = data_preprocess.read_data('./data/tiny_train_input.csv', './data/category_emb', criteo_num_feat_dim, feature_dim_start=0, dim=39)
test_dict = data_preprocess.read_data('./data/tiny_test_input.csv', './data/category_emb', criteo_num_feat_dim, feature_dim_start=0, dim=39)
#result_dict = data_preprocess.read_data('./data/large/train.csv', './data/large/criteo_feature_map', criteo_num_feat_dim, feature_dim_start=1, dim=39)
#test_dict = data_preprocess.read_data('./data/large/valid.csv', './data/large/criteo_feature_map', criteo_num_feat_dim, feature_dim_start=1, dim=39)

You can move data folder to see how it is processed
