### ISSUE TITLE
what does v in the paper mean?

### ISSUE THREAD

**Issue by sangyx** [WayneDW/sDeepFwFM#5]
Hi, thanks for sharing your work. I have a question. The equation of FwFM in the paper is:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/32364921/152316588-83da093c-7aa6-4b68-bd89-dbcffd32456f.png">

What does the v in the above equation mean?

**Comment by WayneDW** [comment]
If I remember correctly, it should be some linear embedding vector for a field? This linear term may have other representations, however, engineering performance shows a superiority that it enjoys both computational efficiency and good prediction power.
