### ISSUE TITLE
DeepLight paper question - does Table 1 have a typ0?

### ISSUE THREAD

**Issue by drei34** [WayneDW/sDeepFwFM#7]
Hi,

Thanks for this code! I was looking at the paper: https://arxiv.org/abs/2002.06987 and I see that on Table 1 the shallow layer of DeepFM is O(nk) while that of DeepFwFM is O(n^2*k). I am wondering why this is. Aren't the formulas the same except that the DeepFwFM term has an R matrix term? Should they not both be O(n^2*k) since both terms are the same except DeepFM has 1's where DeepFwFM has R's?

**Comment by WayneDW** [comment]
Thanks for your interest. FM is more computationally efficient (if you check the computations carefully), while FwFM doesn't have the speed-ups as in the FM module, which is why the computation is slower than FM.

**Comment by drei34** [comment]
Thanks! I actually am unsure why though and I guess I have to press you a little more. I mean the only difference between the formulas in DeepFM and FwFM is the R, right? I mean the shallow parts are the differences so it seems FwFM has another O(n) in complexity but I'm unsure why. It seems that if you take x which is dimension m then only n of the 1/0 elements will be nonzero. An inner product between two vectors takes O(k) time if the dimensions of all vectors is k. The linear part then in FwFM takes O(nk) time while that in DeepFM is O(n). **The part requiring the quadratic term in DeepFM is O(k * n^2) since there are exactly n^2 / 2 products xi*xj equal to 1 and <ei, ej> is O(k)**. FwFM this is exactly the same but we have a term R and this takes O(1) time. What is wrong with my bold statement then?

<img width="368" alt="image" src="https://user-images.githubusercontent.com/2657501/202947867-1ecda414-fd97-48ed-9d51-7802478223e6.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/2657501/202947992-e65c9c3a-67a9-4d4b-9f1a-1cc7c29d1641.png">

**Comment by drei34** [comment]
I.e. it seems that DeepFM is O(n) + O(n^2 * k) while FwFM is O(nk) + O(n^2k) ... So FwFM might be slower but I am unsure where the O(n*k) is coming from for DeepFM ...
